version: "3"
services:
  app:
    build: .
    tty: true
    ports: # external:internal
      - "28080:80"
    volumes: 
      - "./app:/opt/app"
      - "./input:/opt/input"
    # restart: on-failure