version: "3"
services:
  app:
    build: .
    tty: true
    ports: # external:internal
      - "28080:80"
    networks:
      - docker_web_network
    # restart: on-failure
    volumes: 
      - "./app:/opt/app"
      - "./input:/opt/input"
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13.13-bullseye
  #   tty: true
  #   networks:
  #     - docker_web_network
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

networks:
  docker_web_network:
    driver: bridge