version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-meme-pam-explorer-app-20240126.040832
    tty: true
    ports:
      - "28080:80"
    environment:
      - LOCAL_VOLUMN_PATH=/opt/app/
      - CONTAINER_NAME=docker-web-meme-pam-explorer-app
    volumes: 
      - "__SOURCE_INPUT__:/opt/input/"
      - "__SOURCE_APP__:/opt/app/"
    networks:
      - docker_web_network

networks:
  docker_web_network:
    driver: bridge