version: "3"
services:
  app:
    image: pudding/docker-web:docker-web-meme-pam-explorer-app-20240320.090350
    tty: true
    ports:
      - "__EXT_PORT__:80"
    volumes: 
      - "__SOURCE_INPUT__:/opt/input/"
      - "__SOURCE_APP__:/opt/app/"
    environment:
      - LOCAL_VOLUMN_PATH=/opt/app/
      - CONTAINER_NAME=docker-web-meme-pam-explorer-app
    # restart: on-failure